export const userTypes = {
    SIGN_IN_START:'SIGN_IN_START',
    SIGN_IN_SUCCESS:'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE:'SIGN_IN_FAILURE',
    SIGN_IN_EMAIL_START:'SIGN_IN_EMAIL_START',
    SIGN_IN_EMAIL_SUCCESS:'SIGN_IN_EMAIL_SUCCESS',
    SIGN_IN_EMAIL_FAILURE:'SIGN_IN_EMAIL_FAILURE',
    SIGN_UP_START:'SIGN_UP_START',
    SIGN_UP_SUCCESS:'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE:'SIGN_UP_FAILURE',
    SIGN_OUT:'SIGN_OUT',
    CHECK_USER_SESSION:'CHECK_USER_SESSION'

}